import type { LucideIcon } from "lucide-react";
import {
  Archive,
  ArrowRight,
  Check,
  ChevronRight,
  CircleAlert,
  Clock3,
  Cloud,
  Download,
  ExternalLink,
  FileText,
  Folder,
  HardDrive,
  Home,
  Image,
  Info,
  List,
  Maximize2,
  Menu,
  Minus,
  MessageCircle,
  Music2,
  Pause,
  Play,
  Plus,
  RotateCw,
  Square,
  Search,
  Send,
  Share2,
  ShieldCheck,
  SlidersHorizontal,
  UserRound,
  Video,
  X,
  Zap,
} from "lucide-react";

const icons: Record<string, LucideIcon> = {
  home: Home,
  telegram: Send,
  share: Share2,
  download: Download,
  archive: Archive,
  cloud: Cloud,
  logs: List,
  settings: SlidersHorizontal,
  search: Search,
  plus: Plus,
  pause: Pause,
  play: Play,
  close: X,
  minimize: Minus,
  maximize: Maximize2,
  restore: Square,
  refresh: RotateCw,
  folder: Folder,
  user: UserRound,
  drive: HardDrive,
  shield: ShieldCheck,
  bolt: Zap,
  image: Image,
  video: Video,
  file: FileText,
  clock: Clock3,
  alert: CircleAlert,
  check: Check,
  arrow: ArrowRight,
  chevron: ChevronRight,
  external: ExternalLink,
  filter: SlidersHorizontal,
  menu: Menu,
  info: Info,
  message: MessageCircle,
  music: Music2,
};

export function Icon({ name, size = 18, className }: { name: string; size?: number; className?: string }) {
  const Component = icons[name] ?? Info;
  return <Component aria-hidden="true" className={className} size={size} strokeWidth={1.75} />;
}
